import Head from "next/head";
import React from "react";
import Navbar from "../src/components/Navbar/Navbar";

const messaging = () => {
  return (
    <div>
      <Head>
        <title>Messaging</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  );
};

export default messaging;
